<h1 id="tocheading">Table of Contents</h1>
<br />
<div id="toc"><ul class="toc"><li><a href="#1.-Quick-look-at-the-dataset">1. Quick look at the dataset</a><a class="anchor-link" href="#1.-Quick-look-at-the-dataset">¶</a></li><ul class="toc"><li><a href="#1.1.-First-few-rows">1.1. First few rows</a><a class="anchor-link" href="#1.1.-First-few-rows">¶</a></li><li><a href="#1.2.-Data-formats">1.2. Data formats</a><a class="anchor-link" href="#1.2.-Data-formats">¶</a></li></ul><li><a href="#2.-Cleaning-the-data">2. Cleaning the data</a><a class="anchor-link" href="#2.-Cleaning-the-data">¶</a></li><ul class="toc"><li><a href="#2.1.-Column-names">2.1. Column names</a><a class="anchor-link" href="#2.1.-Column-names">¶</a></li><li><a href="#2.2.-Normalise-columns">2.2. Normalise columns</a><a class="anchor-link" href="#2.2.-Normalise-columns">¶</a></li><ul class="toc"><li><a href="#2.2.1.-Question,-Answer-and-Category--columns">2.2.1. <code>Question</code>, <code>Answer</code> and <code>Category</code>  columns</a><a class="anchor-link" href="#2.2.1.-Question,-Answer-and-Category--columns">¶</a></li><li><a href="#2.2.2.-Value-column">2.2.2. <code>Value</code> column</a><a class="anchor-link" href="#2.2.2.-Value-column">¶</a></li><li><a href="#2.2.3.-Air-Date-column">2.2.3. <code>Air Date</code> column</a><a class="anchor-link" href="#2.2.3.-Air-Date-column">¶</a></li></ul></ul><li><a href="#3.-What-could-you-potentially-focus-on-to-prepare?">3. What could you potentially focus on to prepare?</a><a class="anchor-link" href="#3.-What-could-you-potentially-focus-on-to-prepare?">¶</a></li><ul class="toc"><li><a href="#3.1.-Words-appearing-in-questions">3.1. Words appearing in questions</a><a class="anchor-link" href="#3.1.-Words-appearing-in-questions">¶</a></li><ul class="toc"><li><a href="#3.1.1.-How-often-is-the-answer-deducible-from-the-question?">3.1.1. How often is the answer deducible from the question?</a><a class="anchor-link" href="#3.1.1.-How-often-is-the-answer-deducible-from-the-question?">¶</a></li><li><a href="#3.1.2.-What-are-the-words-which-recur-in-the-questions-most-often?">3.1.2. What are the words which recur in the questions most often?</a><a class="anchor-link" href="#3.1.2.-What-are-the-words-which-recur-in-the-questions-most-often?">¶</a></li><li><a href="#3.1.3.-Which-words-in-each-question-will-lead-to-better-chance-of-winning-bigger-reward?">3.1.3. Which words in each question will lead to better chance of winning bigger reward?</a><a class="anchor-link" href="#3.1.3.-Which-words-in-each-question-will-lead-to-better-chance-of-winning-bigger-reward?">¶</a></li></ul><li><a href="#3.2.-Categories">3.2. Categories</a><a class="anchor-link" href="#3.2.-Categories">¶</a></li><ul class="toc"><li><a href="#3.2.1.-What-are-the-most-recurring-categories?">3.2.1. What are the most recurring categories?</a><a class="anchor-link" href="#3.2.1.-What-are-the-most-recurring-categories?">¶</a></li><li><a href="#3.2.2.-Which-categories-will-lead-to-better-chance-of-winning-bigger-reward?">3.2.2. Which categories will lead to better chance of winning bigger reward?</a><a class="anchor-link" href="#3.2.2.-Which-categories-will-lead-to-better-chance-of-winning-bigger-reward?">¶</a></li></ul></ul><li><a href="#4.-So,-should-you-prepare-for-it-if-you-are-to-participate-in-Jeopardy!-?">4. So, should you prepare for it if you are to participate in <em><code>Jeopardy!</code></em> ?</a><a class="anchor-link" href="#4.-So,-should-you-prepare-for-it-if-you-are-to-participate-in-Jeopardy!-?">¶</a></li><li><a href="#5.-Tasks-for-later">5. Tasks for later</a><a class="anchor-link" href="#5.-Tasks-for-later">¶</a></li></ul></div>

Project guide: https://www.dataquest.io/m/210/guided-project%3A-winning-jeopardy

Solution by DataQuest: https://github.com/dataquestio/solutions/blob/master/Mission210Solution.ipynb



This project uses data on American game show [Jeopardy!](https://en.wikipedia.org/wiki/Jeopardy!). The big questions I will ask is whether it is feasible to prepare for it and, if so, what to focus on.

`jeopardy.csv` dataset will be used which has been downloaded from DataQuest. It is a sample (19999 entries) from the whole dataset (216930 entries) at https://www.reddit.com/r/datasets/comments/1uyd0t/200000_jeopardy_questions_in_a_json_file/.

The sample contains only about 9% of the whole dataset. Therefore, any observation made here cannot be safely applied to the whole dataset.

# 1. Quick look at the dataset

## 1.1. First few rows

Below are the first five rows of dataset.

In [1]:
from IPython.display import display
import pandas as pd

# read in dataset
jeopardy = pd.read_csv("jeopardy.csv")

# display first 5 rows of dataset
display(jeopardy.head(5))

print("Number of rows:", jeopardy.shape[0])

,Show Number,Air Date,Round,Category,Value,Question,Answer
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was ...",Copernicus
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,No. 2: 1912 Olympian; football star at Carlisl...,Jim Thorpe
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,The city of Yuma in this state has a record av...,Arizona
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", th...",McDonald's
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Co...",John Adams

Number of rows: 19999

## 1.2. Data formats
Most columns have object (string) data type except `Show Number` column which contains integers.

In [2]:
print("Data types for each column")

for c in jeopardy.columns:
    print("{}: {}".format(c, jeopardy[c].dtype))

Data types for each column
Show Number: int64
 Air Date: object
 Round: object
 Category: object
 Value: object
 Question: object
 Answer: object

# 2. Cleaning the data
## 2.1. Column names

Following are the description for all columns (as shown on DataQuest).

*   `Show Number` \-\- the Jeopardy episode number of the show this question was in.
*   `Air Date` \-\- the date the episode aired.
*   `Round` \-\- the round of Jeopardy that the question was asked in. Jeopardy has several rounds as each episode progresses.
*   `Category` \-\- the category of the question.
*   `Value` \-\- the number of dollars answering the question correctly is worth.
*   `Question` \-\- the text of the question.
*   `Answer` \-\- the text of the answer.

Some column names have leading whitespaces, so they will be removed now.

In [3]:
# show original column names
print("Original column names:\n", jeopardy.columns.tolist())
print()

# remove leading white spaces
jeopardy.columns = jeopardy.columns.str.lstrip()

# show updated column names
print("Updated column names:\n", jeopardy.columns.tolist())
print("\n")

Original column names:
 ['Show Number', ' Air Date', ' Round', ' Category', ' Value', ' Question', ' Answer']

Updated column names:
 ['Show Number', 'Air Date', 'Round', 'Category', 'Value', 'Question', 'Answer']

## 2.2. Normalise columns

Now, the data will be converted so that I can work with them.

### 2.2.1. `Question`, `Answer` and `Category`  columns

Items in `Category` column will only be capitalised because infomration will be lost if thoroughly processed.

For `Question` and `Answer` columns, HTML tags, punctuation and [stop words](https://en.wikipedia.org/wiki/Stop_words) will be removed. Also, all characters will be lowercased.

Note that unfortunately the stopwords list from [NLTK library](http://www.nltk.org/) filtering is not perfect, I have not added missing words due to time contraint. Words such as `They've` will not be filtered, but converted into `theyve`.

In [4]:
from nltk.corpus import stopwords
from pprint import pprint
from string import punctuation
from bs4 import BeautifulSoup

import re

def normalise_text(text, thorough=True):
    """
    Strip html tags from text,
    and lowercase text.
    
    If "thorough" is set to be True, also
    remove double qoutes from text,
    exclude stopwords then
    remove punctuation from remaining text.
    Lastly, remove repeated words.
    
    Return output as a list of words.
    """

    # remove HTML tags from text
    t = BeautifulSoup(text, "lxml").get_text()

    # lowercase text
    t = t.lower() if thorough else t.upper()
    
    if thorough:
    
        # remove double quotation marks from text
        t = re.sub("\"", " ", t)

        # load stopwords
        sw = stopwords.words('english')

        # set up punctuation remover
        translator = str.maketrans("", "", punctuation)

        # initiate normalised word list
        t_norm = []

        # for each word which is not a stopword
        for word in t.split(" "):
            if word not in sw:

                # remove punctuation
                w = word.translate(translator)

                # if word is not null and still not a stopword
                if (w != "") and (w not in sw):

                    # add it to normalised list
                    t_norm.append(w)

    # either return a lower-cased string
    # or return a list of further processed text with repeated words removed
    return list(set(t_norm)) if thorough else t

# show example of original text
print("Original text examples")
print(jeopardy["Question"].iloc[1])
print(jeopardy["Answer"].iloc[1])
print(jeopardy["Category"].iloc[1])
print()

# normalise text
jeopardy["clean_question"] = jeopardy["Question"].apply(normalise_text, args=(True,))
jeopardy["clean_answer"] = jeopardy["Answer"].apply(normalise_text, args=(True,))
jeopardy["clean_category"] = jeopardy["Category"].apply(normalise_text, args=(False,))

# show example of updated text
print("Updated text example")
print(jeopardy["clean_question"].iloc[1])
print(jeopardy["clean_answer"].iloc[1])
print(jeopardy["clean_category"].iloc[1])

Original text examples
No. 2: 1912 Olympian; football star at Carlisle Indian School; 6 MLB seasons with the Reds, Giants & Braves
Jim Thorpe
ESPN's TOP 10 ALL-TIME ATHLETES

Updated text example
['reds', 'carlisle', 'indian', '2', 'school', 'olympian', 'mlb', '1912', 'football', 'star', 'braves', 'giants', '6', 'seasons']
['thorpe', 'jim']
ESPN'S TOP 10 ALL-TIME ATHLETES

### 2.2.2. `Value` column

`$` symbol will be removed. Then, its format will be converted from string to integer. "None" will be converted to 0.

In [5]:
import re

def normalise_value(value):
    """
    Remove "$" and "," from value, and
    convert it it into integer.
    
    If value is "None",
    convert it into 0.
    """
    
    # remove "," and "$"
    output_1 = re.sub(",|\$", "", value)
    
    # Change "None" to "0"
    output_2 = re.sub("None", "0", output_1)
    
    return int(output_2)


# show examples of original value
print("Original value examples")
print(jeopardy["Value"].loc[22])
print(jeopardy["Value"].loc[19987])
print()

# noremalise value
jeopardy["clean_value"] = jeopardy["Value"].apply(normalise_value)

# show example of updated text
print("Updated value examples")
print(jeopardy["clean_value"].loc[22])
print(jeopardy["clean_value"].loc[19987])
print()

Original value examples
$2,000
None

Updated value examples
2000
0

### 2.2.3. `Air Date` column

Strings will be converted to `datetime64` format.

This column has no use in this project, but I will do it just to demonstrate it.

In [6]:
# convert string to datetime64
jeopardy["Air Date"] = pd.to_datetime(jeopardy["Air Date"])

# display first 5 rows of converted version
print(jeopardy["Air Date"].head(5))

0   2004-12-31
1   2004-12-31
2   2004-12-31
3   2004-12-31
4   2004-12-31
Name: Air Date, dtype: datetime64[ns]

# 3. What could you potentially focus on to prepare?

If you are to participate in the show, perhaps you could prepare. Or perhaps not?

I will tackle this question by first checking whether any of two potential foci will be useful: **words appearing in questions** or **categories**.

## 3.1. Words appearing in questions

### 3.1.1. How often is the answer deducible from the question?

Could it be that the questions are so obvious no preparation is needed at all? Perhaps part of the answer is given in the question? To answer this, I will do the following for each question and answer pair.

* Count the words which appear both in each question and its answer pair.
* Divide it by the number of words in the answer.

The higher this ratio, the more obvious the question may be.

In [7]:
def get_answer_in_question(series):
    """
    For each row of series (pandas series),
    count the number of words which appear
    in both question and answer.
    
    Divide this number by the number of words in answer.
    
    Return the output.
    Return 0 if answer contains no words.
    """

    # load question and answer
    q_ns = set(series["clean_question"])
    a_ns = set(series["clean_answer"])
    
    # return 0 if answer contains no words
    if len(a_ns) == 0:
        return 0
    
    # number of words appearing in both question and answer
    overlap = len(a_ns.intersection(q_ns))
    
    # return measure of how many words in answer also appears in question
    return overlap / len(a_ns)

jeopardy["answer_in_question"] = jeopardy.apply(get_answer_in_question, axis=1)
print("Mean ratio of words in answers which also appear in questions is {:.3%}".\
      format(jeopardy["answer_in_question"].mean()))

Mean ratio of words in answers which also appear in questions is 3.838%

So, only a handful of words in answers also appeared in questions. As the questions are not that obvious, you cannot just walk in and expect to answer the questions.

### 3.1.2. What are the words which recur in the questions most often?

If you are to study for it, the words in questions might be used as a guideline.

I will first check the words used again and again across questions. The most recurring words will be displayed with the number of questions they appear in.

In [8]:
from pprint import pprint
from collections import OrderedDict

import operator

def most_recurring_items(col, item):
    """
    Display a table showing item and its frequency in col,
    where col is a column name in pandas dataframe.
    """
    
    def print_repeated_ratio(counter, item):
        """
        item: string label
        counter: a dictionary whose keys are different types of the item
        
        Print ratio of repeated instances of an item.
        """
        
        # get ratio of repeated words
        counter_len = len(counter)
        tot_items = sum(counter.values())

        repeat_ratio = (tot_items - counter_len) / tot_items
        
        print("Total instances of {}:".format(item))
        print(tot_items)
        print()

        print("Ratio of repeat instances:")
        print("({} - {}) / {}) = {}".format(tot_items, counter_len, tot_items, repeat_ratio))
        print()

        print("Around {:.3%} were repeated instances\n\
        across all instances of {},\n\
        (i.e. appearing in more than one question)"\
              .format(repeat_ratio, item))
        print("\n\n")

    # create word counter (key is word, value is count)
    counter = {}
    
    # update counter
    count(counter, col, update_counter)

    # print total number of items
    print("Total number of {}:".format(item))
    print(len(counter))
    print()
    
    # print ratio of repeated instances if item is "words"
    if item == "words":
        print_repeated_ratio(counter, item)

    print("100 most repeated {}".format(item))
    display(pd.DataFrame(sorted(counter.items(), key=operator.itemgetter(1), reverse=True)[:100],
                columns=[item, "Frequency"]))


def count(counter, col, update_counter_func, high_val=False):
    """
    For each row in col (column label in pandas dataframe),
    count number of item (if col == "clean_category")
        or its elements (if col == "clean question")
    and put it into counter (dictionary)
    using (update_counter_func).

    If high_val is True,
    define h_val as the value in "high_value" column, and
    h_val_len as number of entries in "high_value" column.
    """
    
    # number of entries in "high_value" column
    h_val_len = jeopardy["high_value"].shape[0] if high_val else None
    
    for idx, row in jeopardy.iterrows():
        h_val = None if high_val == False else row["high_value"]
        if col == "clean_question":
            for i in row[col]:
                update_counter_func(i, counter, h_val, h_val_len)            
        elif col == "clean_category":
            update_counter_func(row[col], counter, h_val, h_val_len)            
    
    return counter

def update_counter(key, counter, high_val=None, high_val_len=None):
    """
    Update frequencies of key
    into counter (dictionary)

    If high_val and high_val_len are not False,
    count separately for different
    values in "high_value" column.
    """

    if (high_val is None) and (high_val_len is None):

        # count item
        if key in counter:
            counter[key] += 1
        else:
            counter[key] = 1
    else:

        # add item to counter if not already present
        if key not in counter:
            counter[key] = [0] * high_val_len

        # increment count
        counter[key][high_val] += 1


pd.options.display.max_rows = 100
most_recurring_items("clean_question", "words")

Total number of words:
31664

Total instances of words:
166473

Ratio of repeat instances:
(166473 - 31664) / 166473) = 0.8097949817688154

Around 80.979% were repeated instances
        across all instances of words,
        (i.e. appearing in more than one question)



100 most repeated words

        words  Frequency
0         one       1092
1        name        996
2       first        922
3        city        558
4          us        558
5      called        514
6           2        508
7       named        502
8        like        479
9     country        473
10       seen        469
11        man        459
12        new        436
13       type        433
14      state        422
15       clue        409
16       film        408
17       made        395
18       used        381
19      title        369
20       also        365
21       crew        365
22      known        348
23       word        312
24      years        310
25        may        295
26       said        293
27     played        291
28      wrote        283
29     became        282
30       term        274
31      novel        264
32      world        256
33          3        253
34  president        252
35   american        251
36       part        247
37     famous        247
38    capital        247
39     french        241
40          1        237
41       book        234
42       last        233
43       king        229
44       show        217
45       home        214
46     island        209
47       time        209
48       song        208
49       john        207
50        war        206
51      means        205
52      found        204
53        hit        200
54      great        199
55        get        196
56       play        190
57       born        187
58         im        184
59       make        183
60      river        183
61     people        182
62       many        181
63   national        180
64       work        179
65          4        178
66    largest        176
67        day        176
68          5        175
69        old        174
70       life        172
71      group        172
72     around        169
73      comes        169
74       back        167
75       star        166
76      whose        165
77      south        164
78     little        164
79    british        164
80     author        160
81    meaning        160
82      house        159
83      north        159
84      greek        158
85    century        156
86     family        153
87         tv        152
88    musical        152
89    company        151
90        got        151
91       love        150
92      movie        148
93      often        148
94      thats        147
95     series        146
96      latin        146
97       game        145
98        big        145
99    reports        145

OK. Here they are, but they are unimpressive. "One" or "name" is not really a study topic. So, the frequency of a *word* does not seem useful.

One alternative would be use *topics*. Extracting *topics* from questions would require a more fine-tuned method. Unfortunately, though, this cannot be impelemnted due to time constraint and it is currently beyond my ability.

So, a feasible alternative would use *categories* in the `Category` column. This will be done in a later in  [section 3.2.](#3.2.-Categories).

For now, however, I will do one more anlaysis with words. Although this will be just for the sake of demonstration, the same method will be used on categories later on.

### 3.1.3. Which words in each question will lead to better chance of winning bigger reward?

Some questions give more money when answered correctly. If we divide the questions into high- and low-value questions, we can find the words which appear more often in the high-value questions than in low-value ones.

I will use [Chi-squared test](https://en.wikipedia.org/wiki/Chi-squared_test) to find the words whose frequencies in high- and low-value questions are significantly different (p < 0.05). Then, I will select words which appear more often in high-value questions than in low-value ones.

For each selected words, its probability to appear in high-value questions will be calculated (` = (number of selected words) / (number of words in high-value questions)`). This probability will be multiplied by Chi-squared value, which will yield a **score** for each word. Words with highest scores will be considered to be potentially more profitable.

After that, I will sort the selected words by **score** and then by chi-square value, and display the top 100 in the output. It is probably unnecessary to sort output by chi-square value, but I will do so in case words share same scores.

Each row of the output will contain the word, chi-square value, p-value and score.

In [9]:
from scipy.stats import chisquare

def high_value_assign(series, cutoff):
    """
    Return 1 if "Value" is above cutoff.
    Return 0 otherwise.
    """
    
    return 1 if series["clean_value"] > cutoff else 0

def count_high_low_val(col):
    """
    Returns a dictionary where
        each key is
            either a whole item at col
            or an element of the item
            (both will be referred to 
            'item' for simplicity) and
        each value is
            number of occurences of the key
            in low or high value questions.
    
    e.g. {item: [low_count, high_count)]}
    """

    # initiate counter
    counter = {}

    # update counter
    count(counter, col, update_counter, high_val=True)
            
    return counter

def get_highLowVal_chisq(counter, item):
    """
    Return item, chi-squared value, p-value and score
        for each item
            (1) in counter and
            (2) which appears more often in high group questions
                than low-value questions.

    Output structure:
    [(item, chi-square_value, p-value, score), ...]
    
    "score" shows potential fruitfulness of item.
    score = (probability of word appearing in high-value question) * (chi-square_value)
    """
    
    # set number of items with highest significance to display
    disp_num = 100

    # get numbers of high and low value questions
    high_len = jeopardy[jeopardy["high_value"] == 1].shape[0]
    low_len = jeopardy[jeopardy["high_value"] == 0].shape[0]

    # get total number of questions
    all_len = jeopardy.shape[0]

    # initiate list for chi-squared statistics output
    c_chisq = []

    # iterate over each item in item counter
    high_over_c = 0
    low_over_c = 0

    for i in counter:

        # get counts
        high_obs = counter[i][0]
        low_obs = counter[i][1]

        # get total observed counts
        all_obs = low_obs + high_obs

        # get prevelance in dataset
        prev = all_obs / all_len

        # get expected count of a item appearing in high value question
        high_exp = prev * high_len

        # get expected count of a item appearing in low value question
        low_exp = prev * low_len

        # get chi-squared value and its p value
        chisq, p = chisquare([low_obs, high_obs], [low_exp, high_exp])


        # if chi-square statistics is significant
        if p < 0.05:

            # if items in high-value questions
            # appear more frequently than expected
            if high_obs - high_exp > 0:
                
                # get probability of word appearing in high-value questions
                high_prob = high_obs / high_len
                
                # get score (this is an overal measure of
                # potential fruitfulness of the word)
                score = chisq * high_prob
                
                # update list
                # (last item in the list is a score)
                c_chisq.append((i, chisq, p, score))
    
    # display top disp_num items (sorted by )
    pd.options.display.max_rows = 100
    display(pd.DataFrame(sorted(c_chisq, key=operator.itemgetter(3,1), \
                        reverse=True)[:disp_num], \
                        columns = [item, "Chi-sqaured value", "P-value", "Score"]))
    

# 1. categorise questions as low or high value
cutoff = 800
jeopardy["high_value"] = jeopardy.apply(high_value_assign, axis=1, args=(cutoff,))

# 2. count number of times a word appears in high or low value questions
word_counter = count_high_low_val("clean_question")

# 3. display 100 words which are most heavily prevalent in high-value questions
# (more prevalent ones appear nearer top)
# Output structure is [(item, chi-square_value, p-value, score), ...]
# where higher score being better associated with greater reward
get_highLowVal_chisq(word_counter, "Word")

# delete counter to clear memory
del word_counter

         Word  Chi-sqaured value        P-value       Score
0         one        1057.237256  6.505652e-232  147.319946
1       first         817.647311  7.857238e-180   93.685784
2        name         710.530998  1.533535e-156   82.527667
3          us         539.017905  3.083795e-119   38.353559
4        city         534.679984  2.708951e-118   37.951649
5           2         438.132112   2.760403e-97   27.431013
6        like         431.784884   6.643699e-96   25.828778
7        seen         415.082964   2.868878e-92   24.178185
8     country         398.693069   1.060323e-88   23.084426
9      called         375.325915   1.295983e-83   22.647849
10        man         378.118163   3.196460e-84   21.101816
11        new         367.385493   6.941587e-82   19.605853
12      state         371.289350   9.805371e-83   19.425672
13       film         375.555658   1.154992e-83   19.255906
14      named         319.354853   2.001836e-71   18.100859
15       made         356.696215   1.475648e-79   17.604644
16       type         310.630613   1.591660e-69   15.710303
17       said         322.406253   4.332846e-72   12.538646
18       also         279.140852   1.155634e-62   12.121743
19      title         267.962885   3.154248e-60   11.589605
20      years         292.253734   1.605072e-65   11.467926
21        may         295.054476   3.937894e-66   11.217627
22       used         247.116764   1.104143e-55   10.687994
23     played         282.083101   2.640330e-63   10.478497
24     became         258.702395   3.291286e-58    9.158805
25    capital         262.637084   4.567785e-59    8.519445
26      known         213.350815   2.551760e-48    8.297390
27          1         259.031400   2.790289e-58    8.131436
28      wrote         223.996804   1.215104e-50    7.617610
29      world         233.650255   9.534753e-53    7.497671
30  president         233.711286   9.246993e-53    7.418112
31       time         248.577522   5.303421e-56    7.066295
32       term         206.001666   1.023831e-46    6.682300
33       word         188.069613   8.388878e-43    6.527006
34       book         217.017623   4.045162e-49    6.396229
35   american         198.863236   3.697453e-45    5.999885
36        hit         223.713308   1.401027e-50    5.969330
37       song         213.789996   2.046588e-48    5.779116
38       part         194.738583   2.938096e-44    5.773554
39       show         206.730300   7.099827e-47    5.696440
40     famous         186.963947   1.462390e-42    5.477841
41          3         183.582270   8.004000e-42    5.442795
42      novel         179.001111   8.007956e-41    5.431844
43       star         225.037938   7.203376e-51    5.298242
44        war         191.997330   1.165115e-43    4.989118
45       many         204.970685   1.718628e-46    4.968770
46       last         166.962003   3.409806e-38    4.542391
47    largest         193.885555   4.510682e-44    4.530984
48        day         193.885555   4.510682e-44    4.530984
49          4         189.084243   5.037597e-43    4.418781
50        get         179.417004   6.497005e-41    4.411894
51       clue         111.871797   3.811788e-26    4.175194
52       home         159.857824   1.215380e-36    4.042446
53       born         168.962080   1.246989e-38    3.948538
54       life         162.847022   2.701727e-37    3.550031
55       make         156.499849   6.583256e-36    3.520837
56      great         149.278649   2.492484e-34    3.514583
57          5         156.438051   6.791169e-36    3.410317
58      north         161.256082   6.014730e-37    3.318489
59       game         167.259323   2.936199e-38    3.267012
60     series         164.763927   1.030101e-37    3.218270
61      could         165.026557   9.026277e-38    3.194619
62      found         136.668692   1.424802e-31    3.193862
63   national         146.320497   1.104781e-33    3.189756
64       john         135.187376   3.004355e-31    3.182821
65     people         142.460050   7.714182e-33    3.105599
66     island         131.871578   1.596180e-30    3.104755
67      group         146.088778   1.241461e-33    3.082794
68       king         124.446712   6.726140e-29    3.081868
69      means         131.406489   2.017581e-30    3.047971
70         im         138.701003   5.120161e-32    3.023653
71        old         142.108494   9.207855e-33    2.998802
72     around         143.991309   3.568543e-33    2.988309
73       crew          90.847653   1.551710e-21    2.962768
74         tv         146.222278   1.160775e-33    2.830602
75        got         144.092610   3.391119e-33    2.764246
76    popular         162.472152   3.262406e-37    2.748483
77    musical         141.916757   1.014105e-32    2.722505
78      later         146.930804   8.125644e-34    2.690571
79       back         131.903942   1.570369e-30    2.645440
80       work         125.121176   4.787981e-29    2.596690
81    company         135.581699   2.463210e-31    2.553684
82     states         140.272881   2.320286e-32    2.519726
83       play         117.341969   2.416035e-27    2.496638
84        big         135.662404   2.365098e-31    2.484226
85       year         138.377539   6.025912e-32    2.413281
86     family         127.380950   1.533279e-29    2.377008
87      movie         129.332009   5.737235e-30    2.368305
88      river         114.744866   8.950280e-27    2.361335
89    british         118.258587   1.521949e-27    2.268651
90        sea         131.768120   1.681572e-30    2.252054
91       says         125.167025   4.678621e-29    2.226550
92     author         117.953217   1.775262e-27    2.221651
93       good         127.261199   1.628643e-29    2.219414
94       york         132.156959   1.382451e-30    2.189555
95         10         137.958405   7.441938e-32    2.189434
96  character         125.150441   4.717886e-29    2.182603
97     little         114.532901   9.959993e-27    2.177204
98      often         121.195685   3.462387e-28    2.177041
99      house         115.985154   4.788679e-27    2.164355

Again, this list of *words* do not seem so helpful.

Let me finally analyse categories, which should be more useful.

## 3.2. Categories

### 3.2.1. What are the most recurring categories?

In [10]:
most_recurring_items("clean_category", "Categories")

Total number of Categories:
3579

100 most repeated Categories

                  Categories  Frequency
0                 TELEVISION         51
1             U.S. GEOGRAPHY         50
2                 LITERATURE         45
3                    HISTORY         40
4           AMERICAN HISTORY         40
5             BEFORE & AFTER         40
6                    AUTHORS         39
7               WORD ORIGINS         38
8             WORLD CAPITALS         37
9                     SPORTS         36
10           BODIES OF WATER         36
11                   SCIENCE         35
12          SCIENCE & NATURE         35
13                 MAGAZINES         35
14                RHYME TIME         35
15           WORLD GEOGRAPHY         33
16             ANNUAL EVENTS         32
17            HISTORIC NAMES         32
18             WORLD HISTORY         32
19         IN THE DICTIONARY         31
20                     BIRDS         31
21      FICTIONAL CHARACTERS         31
22          TRAVEL & TOURISM         30
23                  MEDICINE         30
24                 POTPOURRI         30
25                   ISLANDS         30
26                     OPERA         30
27           U.S. PRESIDENTS         30
28                    BALLET         29
29                       ART         28
30            STATE CAPITALS         27
31             ORGANIZATIONS         27
32                NONFICTION         27
33       BUSINESS & INDUSTRY         26
34                    PEOPLE         26
35                THE MOVIES         26
36               U.S. CITIES         26
37               BRAND NAMES         26
38                   ANATOMY         25
39             ART & ARTISTS         25
40                FOOD FACTS         25
41    HOLIDAYS & OBSERVANCES         25
42           MUSICAL THEATRE         25
43                    SAINTS         25
44                   MAMMALS         25
45                   MUSEUMS         25
46   THE AMERICAN REVOLUTION         25
47              FAMOUS NAMES         24
48                SCIENTISTS         23
49       AMERICAN LITERATURE         23
50                 FURNITURE         23
51                 ASTRONOMY         22
52               SHAKESPEARE         21
53                 AMERICANA         21
54           GENERAL SCIENCE         20
55             THE CIVIL WAR         20
56              COMMON BONDS         20
57            POETS & POETRY         20
58                 POP MUSIC         20
59            4-LETTER WORDS         20
60                 ACTRESSES         20
61                     SHIPS         20
62                    NATURE         20
63               DOUBLE TALK         20
64            STUPID ANSWERS         20
65                QUOTATIONS         20
66     WORD & PHRASE ORIGINS         20
67      ACTORS & THEIR ROLES         20
68                      FOOD         20
69                 GEOGRAPHY         20
70                    AWARDS         19
71                    EUROPE         18
72              WORLD CITIES         18
73          AMERICAN AUTHORS         17
74                   INSECTS         17
75  SAME FIRST & LAST LETTER         17
76         PEOPLE IN HISTORY         16
77            TRANSPORTATION         16
78                 THE BIBLE         16
79               THE TITANIC         16
80                 MOUNTAINS         16
81                 LANGUAGES         16
82           CLASSICAL MUSIC         16
83             NAME THE POET         16
84                 EXPLORERS         16
85               FIRST NAMES         16
86             ANCIENT TIMES         16
87             SCIENCE CLASS         15
88            FROM THE GREEK         15
89             EARLY AMERICA         15
90                 THE 1990S         15
91                  RELIGION         15
92                 PEN NAMES         15
93              SCIENCE GUYS         15
94      CELEBRITY RHYME TIME         15
95     FIRST NAME'S THE SAME         15
96                   EPONYMS         15
97       CROSSWORD CLUES "F"         15
98                GOVERNMENT         15
99                     DANCE         15

OK, the good news is that categories seem more informative than words in questions.

The bad news, however, is that the categories are still rather too broad to be considered foci. Besides, the questions span across the categories, none of which show obvious dominance.

This means that there will be **a lot** of categories to study.

But, I will do continue with the analysis to at least find the most potentially profitable category.

### 3.2.2. Which categories will lead to better chance of winning bigger reward?

This is equivalent to section [3.1.3](#3.1.3.-Which-words-in-each-question-will-lead-to-better-chance-of-winning-bigger-reward?) where reasoning and procedure are explained.

In [11]:
# count number of times a category appears in high or low value questions
category_counter = count_high_low_val("clean_category")

# display 100 categories which are most heavily prevalent in high-value questions
# (more prevalent ones appear nearer top)
get_highLowVal_chisq(category_counter, "clean_category")

# delete counter to clear memory
del category_counter

              clean_category  Chi-sqaured value       P-value     Score
0                 TELEVISION          88.475484  5.146882e-21  0.694349
1                    AUTHORS          59.684007  1.113780e-14  0.343490
2                    HISTORY          56.672545  5.147728e-14  0.326159
3                      BIRDS          63.801323  1.376211e-15  0.322678
4            BODIES OF WATER          58.078258  2.518949e-14  0.313991
5             U.S. GEOGRAPHY          45.899266  1.244926e-11  0.288171
6                     SPORTS          52.596766  4.095631e-13  0.275184
7           TRAVEL & TOURISM          55.173937  1.103219e-13  0.259801
8                  MAGAZINES          50.248681  1.354457e-12  0.254135
9                 FOOD FACTS          55.414809  9.759840e-14  0.231942
10            WORLD CAPITALS          44.701589  2.294710e-11  0.226081
11                LITERATURE          39.631797  3.066497e-10  0.221175
12                RHYME TIME          45.089291  1.882520e-11  0.220178
13       BUSINESS & INDUSTRY          51.483697  7.219415e-13  0.215488
14               U.S. CITIES          51.483697  7.219415e-13  0.215488
15           WORLD GEOGRAPHY          45.577913  1.466864e-11  0.214615
16              FAMOUS NAMES          46.570802  8.836720e-12  0.178681
17              COMMON BONDS          49.755842  1.741189e-12  0.173547
18                    NATURE          49.755842  1.741189e-12  0.173547
19            STATE CAPITALS          42.165683  8.385874e-11  0.169133
20             ORGANIZATIONS          42.165683  8.385874e-11  0.169133
21             ANNUAL EVENTS          38.267695  6.167525e-10  0.166846
22             WORLD HISTORY          38.267695  6.167525e-10  0.166846
23    HOLIDAYS & OBSERVANCES          43.028362  5.395203e-11  0.165090
24                   MAMMALS          43.028362  5.395203e-11  0.165090
25          AMERICAN HISTORY          33.407792  7.472399e-09  0.163135
26                    PEOPLE          39.789338  2.828851e-10  0.152662
27                 POTPOURRI          33.791274  6.135345e-09  0.135542
28                 FURNITURE          38.205848  6.366133e-10  0.133261
29              WORD ORIGINS          29.358687  6.014628e-08  0.133123
30                THE MOVIES          34.506361  4.248605e-09  0.126375
31               BRAND NAMES          34.506361  4.248605e-09  0.126375
32      FICTIONAL CHARACTERS          31.411860  2.087022e-08  0.125998
33                NONFICTION          31.836555  1.677065e-08  0.116597
34                      FOOD          36.782625  1.320620e-09  0.115467
35                   MUSEUMS          32.206637  1.386165e-08  0.112336
36                   INSECTS          35.604514  2.417267e-09  0.099350
37                  PROVERBS          37.316882  1.004116e-09  0.097620
38              FIRST LADIES          37.316882  1.004116e-09  0.097620
39            HISTORIC NAMES          25.133990  5.348183e-07  0.096433
40            4-LETTER WORDS          31.029479  2.541390e-08  0.091995
41                     SHIPS          31.029479  2.541390e-08  0.091995
42            STUPID ANSWERS          31.029479  2.541390e-08  0.091995
43      ACTORS & THEIR ROLES          31.029479  2.541390e-08  0.091995
44                    SAINTS          27.382545  1.669312e-07  0.090734
45         PEOPLE IN HISTORY          33.134699  8.599038e-09  0.086680
46                 THE BIBLE          33.134699  8.599038e-09  0.086680
47                 EXPLORERS          33.134699  8.599038e-09  0.086680
48               SHAKESPEARE          28.066825  1.171977e-07  0.083212
49                 AMERICANA          28.066825  1.171977e-07  0.083212
50                    BALLET          23.023305  1.600495e-06  0.080305
51                    AWARDS          28.657497  8.637892e-08  0.079965
52                 ASTRONOMY          25.410045  4.634983e-07  0.075335
53                  BASEBALL          30.667281  3.062865e-08  0.074877
54       THE HISTORY CHANNEL          30.667281  3.062865e-08  0.074877
55           U.S. PRESIDENTS          21.177104  4.187371e-06  0.073865
56   THE AMERICAN REVOLUTION          22.949633  1.663020e-06  0.072043
57             THE CIVIL WAR          25.765309  3.855565e-07  0.071895
58                QUOTATIONS          25.765309  3.855565e-07  0.071895
59                 GEOGRAPHY          25.765309  3.855565e-07  0.071895
60              WORLD CITIES          26.298383  2.925335e-07  0.068796
61               THE TITANIC          27.075944  1.956171e-07  0.066108
62             ANCIENT TIMES          27.075944  1.956171e-07  0.066108
63      19TH CENTURY AMERICA          28.202774  1.092479e-07  0.063941
64          NATIONAL ANTHEMS          29.853505  4.659537e-08  0.062477
65          SCIENCE & NATURE          16.797173  4.159523e-05  0.061517
66                     OPERA          17.624349  2.691206e-05  0.058399
67           MUSICAL THEATRE          18.907902  1.371833e-05  0.056058
68                 THE 1990S          24.669648  6.804745e-07  0.055930
69      CELEBRITY RHYME TIME          24.669648  6.804745e-07  0.055930
70                     DANCE          24.669648  6.804745e-07  0.055930
71               ODDS & ENDS          24.669648  6.804745e-07  0.055930
72                     SONGS          24.669648  6.804745e-07  0.055930
73            THE HUMAN BODY          24.669648  6.804745e-07  0.055930
74          GUINNESS RECORDS          24.669648  6.804745e-07  0.055930
75            POETS & POETRY          20.990115  4.616592e-06  0.054910
76                 POP MUSIC          20.990115  4.616592e-06  0.054910
77               DOUBLE TALK          20.990115  4.616592e-06  0.054910
78         SPACE EXPLORATION          25.741848  3.902720e-07  0.053872
79       AMERICAN LITERATURE          18.807433  1.446025e-05  0.052480
80                    EUROPE          21.224370  4.085368e-06  0.051821
81                 MOUNTAINS          21.628408  3.309141e-06  0.049035
82                   SCIENCE          13.873100  1.955779e-04  0.048389
83                 LEFTOVERS          22.274994  2.362633e-06  0.046617
84                   ANIMALS          23.285401  1.396561e-06  0.044670
85  NEW YORK TIMES HEADLINES          24.877921  6.107795e-07  0.043387
86        BETTER KNOWN AS...          24.877921  6.107795e-07  0.043387
87                HODGEPODGE          24.877921  6.107795e-07  0.043387
88                   ZOOLOGY          24.877921  6.107795e-07  0.043387
89                  ANAGRAMS          24.877921  6.107795e-07  0.043387
90          AMERICAN AUTHORS          18.992251  1.312504e-05  0.043059
91                   ANATOMY          15.257351  9.381093e-05  0.042574
92             ART & ARTISTS          15.257351  9.381093e-05  0.042574
93                 ACTRESSES          16.703896  4.369118e-05  0.040784
94            BEFORE & AFTER          11.105623  8.606638e-04  0.040673
95                GOVERNMENT          19.323982  1.103121e-05  0.040441
96                  POLITICS          19.323982  1.103121e-05  0.040441
97                   PHYSICS          19.323982  1.103121e-05  0.040441
98       MUSICAL INSTRUMENTS          19.323982  1.103121e-05  0.040441
99             THE 50 STATES          19.894669  8.182818e-06  0.038166

# 4. So, should you prepare for it if you are to participate in *`Jeopardy!`* ?

My answer is a **no** There is simply too much ground to cover.


# 5. Tasks for later

It will not be worth studying for it no matter what, but the method could be fine-tuned to better identify categories which are potentially more profitable.

I used high- and low-value categorisation to judge potential profit, but it would be better to use the `Value` column.